In [3]:
import numpy as np

In [4]:
a1d = np.array([1,2,3])

In [3]:
a1d # one D Array = Vector

array([1, 2, 3])

In [4]:
type(a1d)

numpy.ndarray

In [5]:
a2d = np.array([[1,2,3],[4,5,6]])

In [6]:
a2d # Two D Array = Matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
type(a2d)

numpy.ndarray

In [6]:
a3d = np.array([[[1,2,3],[4,5,6],[5,6,9]],[[1,2,3],[4,5,6],[5,6,9]]])

In [9]:
a3d # Matrix

array([[[1, 2, 3],
        [4, 5, 6],
        [5, 6, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [5, 6, 9]]])

In [3]:
a3d.shape

(2, 3, 3)

In [7]:
a2d.shape

(2, 3)

In [9]:
a1d.shape

(3,)

In [12]:
a3d.ndim # Daimention btata hay yay function a1d.ndim | a2d.ndim | a3d.ndim

3

In [14]:
a3d.dtype

dtype('int64')

In [15]:
a3d.size

18

In [16]:
type(a3d)

numpy.ndarray

In [7]:
import pandas as pd

In [23]:
df = pd.DataFrame(a2d)

In [21]:
df

0  1  2
0  1  2  3
1  4  5  6

# Creating Numpy Arrays

In [8]:
#Zeros
#Ones
#Randoms

ones = np.ones((2,3))

In [33]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
zeros = np.zeros((2,3))

In [35]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [46]:
range_array = np.arange(1,11)

In [47]:
range_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
random_matrix = np.random.randint(0,10,size=(3,5)) # Manual range start and stop

In [51]:
random_matrix

array([[3, 5, 3, 5, 7],
       [2, 9, 4, 9, 6],
       [8, 9, 2, 7, 1]])

In [52]:
random_matrix.size

15

In [53]:
random_matrix.shape

(3, 5)

In [54]:
random_matrix.dtype

dtype('int64')

In [11]:
#Generate random matrix
rand_matrix = np.random.rand(3,5) # Auto Range 0-1

In [56]:
rand_matrix

array([[0.61652253, 0.77253661, 0.27506208, 0.9183925 , 0.42985131],
       [0.40147001, 0.50788217, 0.48975497, 0.91915305, 0.59622204],
       [0.27625901, 0.94844856, 0.85942666, 0.08998179, 0.82285343]])

In [67]:
rand_matrix.sum()

8.390649800271031

In [68]:
# Generate random matrix with fix values using seed method
np.random.seed(seed=0)
rand_matrix = np.random.rand(3,5) # Auto Range 0-1

In [12]:
rand_matrix

array([[0.60339289, 0.69742362, 0.31408391, 0.79679366, 0.3883667 ],
       [0.78802626, 0.54386597, 0.07230986, 0.02497044, 0.40494161],
       [0.53262661, 0.05424099, 0.29006223, 0.7035109 , 0.97305552]])

In [69]:
rand_matrix.sum()

9.042960048565472

# Accessing Elements

In [70]:
a3d

array([[[1, 2, 3],
        [4, 5, 6],
        [5, 6, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [5, 6, 9]]])

In [71]:
a2d

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
a2d[0]

array([1, 2, 3])

In [73]:
a2d[1]

array([4, 5, 6])

In [75]:
a3d[0][0]

array([1, 2, 3])

In [76]:
a3d[:2,:1]

array([[[1, 2, 3]],

       [[1, 2, 3]]])

In [81]:
a3d[:2,:1,:2]

array([[[1, 2]],

       [[1, 2]]])

In [13]:
arandom = np.random.randint(10, size=(2,3,4,5))

In [14]:
arandom[:1,:1,:1,:1]

array([[[[0]]]])

# Manipulation

In [107]:
a1d

array([1, 2, 3])

In [108]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [109]:
a1d + ones # Numpy used Broad-Casting method for maping arrays

array([[2., 3., 4.],
       [2., 3., 4.]])

In [110]:
a1d*a2d

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [111]:
a1d/a2d

array([[1.  , 1.  , 1.  ],
       [0.25, 0.4 , 0.5 ]])

In [112]:
a1d//a2d

array([[1, 1, 1],
       [0, 0, 0]])

In [113]:
a1d**2

array([1, 4, 9])

In [114]:
np.square(a1d)

array([1, 4, 9])

In [115]:
a1d+ones

array([[2., 3., 4.],
       [2., 3., 4.]])

In [116]:
np.add(a1d,ones)

array([[2., 3., 4.],
       [2., 3., 4.]])

# Agregations

In [7]:
sum(a1d) # this is python method :: Slower

6

In [8]:
np.sum(a1d) # this is numpy method :: Faster

6

In [9]:
np.max(a1d)

3

In [10]:
np.min(a1d)

1

In [12]:
# mean

np.mean(a1d)

2.0

In [13]:
# variance
np.var(a1d)

0.6666666666666666

In [14]:
# standard deviation manually
np.sqrt(np.var(a1d))

0.816496580927726

In [15]:
#Biult in method standard deviation
np.std(a1d)

0.816496580927726

# Matrix Multiplication

### Dot product vs Element wise multiplication

In [15]:
np.random.seed(seed=0)
matrix_1  = np.random.randint(10, size=(4,3))
matrix_2 = np.random.randint(10,size=(4,3))

In [18]:
matrix_1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6]])

In [19]:
matrix_2

array([[8, 8, 1],
       [6, 7, 7],
       [8, 1, 5],
       [9, 8, 9]])

In [20]:
# Element wise multiplication
matrix_1 * matrix_2

array([[40,  0,  3],
       [18, 49, 63],
       [24,  5, 10],
       [36, 56, 54]])

In [16]:
matrix_1.dot(matrix_2.T) # Transpose swaps rows into columns and columns into rows

array([[ 43,  51,  55,  72],
       [ 89, 130,  76, 164],
       [ 66,  67,  39,  85],
       [ 94, 115,  69, 146]])

# Reshape and Transpose

In [24]:
# swap rows into columns and columns into rows
a2d

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
a2d.shape

(2, 3)

In [26]:
a2d.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [27]:
a2d.T.shape

(3, 2)

In [29]:
a2d.reshape(2,3,1)

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [30]:
a2d.reshape(2,3,1).shape

(2, 3, 1)

In [20]:
np.random.seed(seed=0)
item_amount = np.random.randint(20,size=(5,3))
item_amount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [18]:
item_price = np.array([12,8,11])
item_price

array([12,  8, 11])

In [21]:
t_price = item_price.dot(item_amount.T)

In [47]:
t_price

array([264, 137, 458, 228, 137])

In [48]:
import pandas as pd

In [22]:
price = pd.DataFrame(t_price,index=['Monday','Teusday','Wednesday','Thursday','Friday'],columns=['item_price'])

In [51]:
price

item_price
Monday            264
Teusday           137
Wednesday         458
Thursday          228
Friday            137

In [23]:

item_price_df = pd.DataFrame(item_price.reshape(1,3),index=['item_price'],columns=['item1','item2','item3'])

In [36]:
item_price_df

item1  item2  item3
item_price     12      8     11

In [24]:
item_price_df.shape,item_amount.T.shape

((1, 3), (3, 5))

In [25]:
total_price = item_price_df.dot(item_amount.T)

In [26]:
total_price

0    1    2    3    4
item_price  264  137  458  228  137

In [27]:
weekly_sales = pd.DataFrame(item_amount,index=['Monday','Teusday','Wednesday','Thursday','Friday'],columns=['item1','item2','item3'])

In [28]:
weekly_sales

item1  item2  item3
Monday        12     15      0
Teusday        3      3      7
Wednesday      9     19     18
Thursday       4      6     12
Friday         1      6      7

In [29]:
weekly_sales['Total'] = price

In [30]:
weekly_sales

item1  item2  item3  Total
Monday        12     15      0    264
Teusday        3      3      7    137
Wednesday      9     19     18    458
Thursday       4      6     12    228
Friday         1      6      7    137

In [34]:
# comparison operator
a1d

array([1, 2, 3])

In [35]:
a2d

array([[1, 2, 3],
       [4, 5, 6]])

# Sorting Arrays

In [36]:
random_matrix = np.random.randint(10, size=(3,5))
random_matrix

array([[7, 8, 1, 5, 9],
       [8, 9, 4, 3, 0],
       [3, 5, 0, 2, 3]])

In [37]:
np.sort(random_matrix)

array([[1, 5, 7, 8, 9],
       [0, 3, 4, 8, 9],
       [0, 2, 3, 3, 5]])

In [38]:
np.sort(random_matrix,axis=1) # Rows Sorting

array([[1, 5, 7, 8, 9],
       [0, 3, 4, 8, 9],
       [0, 2, 3, 3, 5]])

In [39]:
np.sort(random_matrix,axis=0) # Columns Sorting

array([[3, 5, 0, 2, 0],
       [7, 8, 1, 3, 3],
       [8, 9, 4, 5, 9]])

In [40]:
np.argsort(random_matrix)

array([[2, 3, 0, 1, 4],
       [4, 3, 2, 0, 1],
       [2, 3, 0, 4, 1]])

In [46]:
np.argmin(random_matrix,axis=1)

array([2, 4, 2])

In [47]:
np.argmin(random_matrix,axis=0)

array([2, 2, 2, 2, 1])

In [48]:
np.argmax(random_matrix)

4

In [49]:
np.argmax(random_matrix,axis=1)

array([4, 1, 1])

In [50]:
np.argmax(random_matrix,axis=0)

array([1, 1, 1, 0, 0])

# Image data read

In [51]:
from matplotlib.image import imread

In [54]:
img_data = imread('mwa.jpg')

In [55]:
img_data

array([[[61, 68, 78],
        [64, 71, 81],
        [66, 73, 83],
        ...,
        [21, 19, 22],
        [14, 12, 15],
        [21, 19, 22]],

       [[67, 74, 84],
        [70, 77, 87],
        [71, 78, 88],
        ...,
        [21, 19, 22],
        [17, 15, 18],
        [26, 24, 27]],

       [[71, 78, 88],
        [72, 79, 89],
        [73, 80, 90],
        ...,
        [19, 17, 20],
        [19, 17, 20],
        [31, 29, 32]],

       ...,

       [[20, 23, 16],
        [21, 24, 17],
        [23, 26, 19],
        ...,
        [ 7,  3,  0],
        [ 7,  3,  0],
        [ 8,  4,  1]],

       [[20, 23, 16],
        [21, 24, 17],
        [23, 26, 19],
        ...,
        [ 7,  3,  0],
        [ 7,  3,  0],
        [ 8,  4,  1]],

       [[20, 23, 16],
        [21, 24, 17],
        [23, 26, 19],
        ...,
        [ 7,  3,  0],
        [ 7,  3,  0],
        [ 8,  4,  1]]], dtype=uint8)

In [56]:
img_data.size

2467755